#! /bin/sh
bspc monitor -d 1 2 3 4 5

bspc config border_width                08
bspc config window_gap                  30
bspc config top_padding                 20
bspc config bottom_padding	            20
bspc config left_padding                15
bspc config right_padding               15
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config focus_follows_pointer       off
#bspc config normal_border_color        "#585c65"
bspc config focused_border_color        "#97999f"
#bspc config active_border_color        "#585c65"
bspc config presel_feedback_color       "#788249"

bspc rule -a Chromium                   desktop='^2'
bspc rule -a Google-chrome              desktop='^2' follow=off border=off
bspc rule -a Pcmanfm                    state=floating
bspc rule -a Skype                      state=floating follow=off desktop='^5' border = off
bspc rule -a URxvt                      state=floating manage=on layer=normal
bspc rule -a Termite                    state=floating manage=on border=off
bspc rule -a st-256color                state=floating manage=on layer=normal
bspc rule -a mpv                        state=floating manage=on layer=normal
bspc rule -a Spotify                    state=floating follow=off desktop='^4' border = off

dunst &


"$HOME"/oxwm/main.sh  && notify-send "starting" "main"
HOMEAP="ATTJ9KDPi2"
currentAP=$(iwconfig | awk -F'"' '/ESSID/ {print $2}')

if [ "$currentAP" = "$HOMEAP" ]; then
    synergys ~/.synergy.conf/synergy.conf
fi

# vim:nowrap
